--INSERT INTO spending(user_id, bank, account_number, subject, monetary_value, store_name, received_date)
--VALUES
--(1, 'Scotiabank', 'Excellent', "Authorization on your credit account", 25.00, "SAFEWAY", "emailReceiveDateHere")